### ISSUE TITLE
cb_makeDataSource方法设置Section没有cb_makeSectionWithData简便

### ISSUE THREAD

**Issue by sunxiang0918** [cocbin/CBTableViewDataSource#7]
是这样, cb_makeSectionWithData 这个方法可以很简单的传入 data即可生成最基本的带样式的表格.但是缺点就是能有一个section.  那么如果想要两个section的话,就必须调用cb_makeDataSource这个方法,而这个方法需要传入的参数非常的多,如果不调用section.cell()还会直接报错,哪怕我只需要UITableViewCell这个,我还是需要注册一次,并且实现adapter()方法.  

期望在使用cb_makeDataSource方法时,对于CBTableViewSectionMaker这个也能有像cb_makeSectionWithData那样的简便实现方式.

**Comment by cocbin** [comment]
Thinks for your advice.  I will optimize in next version.

**Comment by sunxiang0918** [comment]
Thx~~
